[package]
name = "koofr-vault-desktop"
version = "1.0.0"
edition = "2021"

[dependencies]
tauri = { version = "2.0.0", features = ["shell-open"] }
serde_json = "1.0"

[build-dependencies]
tauri-build = { version = "2.0.0" }
